const colors = {
  light: {
    text: '#0A0F1E',
    tint: '#00C896',
    background: '#F2F5FA',
    foreground: '#0A0F1E',
    card: '#FFFFFF',
    cardForeground: '#0A0F1E',
    primary: '#00C896',
    primaryForeground: '#FFFFFF',
    secondary: '#EBF0F9',
    secondaryForeground: '#3A4560',
    muted: '#EBF0F9',
    mutedForeground: '#6B7A99',
    accent: '#00C896',
    accentForeground: '#FFFFFF',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#DDE4EF',
    input: '#DDE4EF',
  },
  dark: {
    text: '#F0F4FF',
    tint: '#00D4AA',
    background: '#0A0F1E',
    foreground: '#F0F4FF',
    card: '#141B2D',
    cardForeground: '#F0F4FF',
    primary: '#00D4AA',
    primaryForeground: '#0A0F1E',
    secondary: '#1C2640',
    secondaryForeground: '#C8D4EE',
    muted: '#1C2640',
    mutedForeground: '#7A89A8',
    accent: '#00D4AA',
    accentForeground: '#0A0F1E',
    destructive: '#FF4757',
    destructiveForeground: '#FFFFFF',
    border: '#1E2A42',
    input: '#1E2A42',
  },
  radius: 14,
};

export default colors;
